INSERT INTO Course (CourseID, Name, Description, MaxDegree, MinDegree, ExamID) VALUES
(1, 'Course 1: Database Systems', 'A comprehensive course on  Database Systems.', 100, 50, 1),
(2, 'Course 2: Network Security', 'A comprehensive course on  Network Security.', 100, 50, 2),
(3, 'Course 3: Big Data', 'A comprehensive course on  Big Data.', 100, 50, 3),
(4, 'Course 4: Mobile App Development', 'A comprehensive course on  Mobile App Development.', 100, 50, 4),
(5, 'Course 5: Python Programming', 'A comprehensive course on  Python Programming.', 100, 50, 5),
(6, 'Course 6: Python Programming', 'A comprehensive course on  Python Programming.', 100, 50, 6),
(7, 'Course 7: Software Engineering', 'A comprehensive course on  Software Engineering.', 100, 50, 7),
(8, 'Course 8: Machine Learning', 'A comprehensive course on  Machine Learning.', 100, 50, 8),
(9, 'Course 9: Artificial Intelligence', 'A comprehensive course on  Artificial Intelligence.', 100, 50, 9),
(10, 'Course 10: Mobile App Development', 'A comprehensive course on  Mobile App Development.', 100, 50, 10),
(11, 'Course 11: Data Science', 'A comprehensive course on  Data Science.', 100, 50, 11),
(12, 'Course 12: Artificial Intelligence', 'A comprehensive course on  Artificial Intelligence.', 100, 50, 12),
(13, 'Course 13: Cloud Computing', 'A comprehensive course on  Cloud Computing.', 100, 50, 13),
(14, 'Course 14: Full Stack Development', 'A comprehensive course on  Full Stack Development.', 100, 50, 14),
(15, 'Course 15: Database Systems', 'A comprehensive course on  Database Systems.', 100, 50, 15),
(16, 'Course 16: Full Stack Development', 'A comprehensive course on  Full Stack Development.', 100, 50, 16),
(17, 'Course 17: Machine Learning', 'A comprehensive course on  Machine Learning.', 100, 50, 17),
(18, 'Course 18: Full Stack Development', 'A comprehensive course on  Full Stack Development.', 100, 50, 18),
(19, 'Course 19: IoT', 'A comprehensive course on  IoT.', 100, 50, 19),
(20, 'Course 20: Software Engineering', 'A comprehensive course on  Software Engineering.', 100, 50, 20),
(21, 'Course 21: IoT', 'A comprehensive course on  IoT.', 100, 50, 21),
(22, 'Course 22: Data Science', 'A comprehensive course on  Data Science.', 100, 50, 22);